#!/usr/bin/env bash
# This script was generated by ChatGPT then tested and corrected

set -e

BASE_DIR=$(pwd)
REPOS=(
  "git@github.com:wilson-gv-project/wilson-analysis.git:main wilson_analysis"
  "git@github.com:wilson-gv-project/wilson-derive.git:main wilson_derive"
  "git@github.com:wilson-gv-project/wilson-experiment.git:main wilson_experiment"
  "git@github.com:wilson-gv-project/wilson-main.git:main wilson_main"
  "git@github.com:wilson-gv-project/wilson-utils.git:main wilson_utils"
  "git@github.com:wilson-gv-project/wilson-intensities.git:restruct2 wilson_intensities"
  "git@github.com:wlevand/CQCParse.git:tests CQCParse"
)

echo "🔄 Cloning repositories..."
for entry in "${REPOS[@]}"; do
  # separate repo+branch from destination
  repo_branch="${entry% *}"
  dest="${entry#* }"
  
  echo ""
  echo "repo_branch:$repo_branch; dest:$dest"

  # separate repo and branch
  gitp="${repo_branch%%:*}"
  rp_branch="${repo_branch#*:}"
  
  repo="$gitp:${rp_branch%%:*}"
  branch="${rp_branch#*:}"
  echo "👉 Cloning $repo into $dest (branch: $branch)"

  if [ ! -d "$dest" ]; then
    git clone --branch "$branch" "$repo" "$dest"
  else
    echo "✅ $dest already exists, skipping clone"
  fi
done

echo "✅ All done!"

