name: wilsonsuite
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - scipy
  - pandas
  - matplotlib
  - plotly
  - altair
  - pip
  - pip:
      - -r requirements.txt
