from ...wilson_utils.printing import (
    use_print_target,
    infoprint,
    debugprint,
    printtest,
    separatorprint,
    coolprint,
    debugfunc,
    debug_deep
)
import io
import re

import sys
from ...wilson_utils import printing as wprinting

from ...wilson_utils.paths import UTILS_ROOT
TESTFILESDIR = UTILS_ROOT + "/tests/"

def test_debugfunc(capsys):
    """
    capsys - pytest caturing stdout/stderr
    """
    wprinting.level = 2
    wprinting.PRINT_TARGET = sys.stdout
    wprinting._styled_print("DEBUG][debugfunc", "95", "hello test_debugfunc", file=sys.stdout)

    captured = capsys.readouterr()
    assert "[DEBUG][debugfunc] hello test_debugfunc" in captured.out

    debugfunc('hello debugfunc', 'yo')
    captured = capsys.readouterr()
    assert "[DEBUG][yo] hello debugfunc" in captured.out


def test_debug_deep(capsys):
    """
    capsys - pytest caturing stdout/stderr
    """
    wprinting.level = 2
    wprinting.PRINT_TARGET = sys.stdout
    wprinting._styled_print("DEBUG DEEP][debug_deep", "95", "hello debug_deep", file=sys.stdout)

    captured = capsys.readouterr()
    assert "[DEBUG DEEP][debug_deep] hello debug_deep" in captured.out

    debug_deep('hello debug_deep', 'yo')
    captured = capsys.readouterr()
    assert "[DEBUG DEEP][yo] hello debug_deep" in captured.out

def test_separatorprint(capsys):
    separatorprint(file=sys.stdout)
    captured = capsys.readouterr()
    assert '---------------  ---------------' in captured.out
    wprinting.PRINT_TARGET = sys.stdout # reseting

def test_coolprint():
    coolprint("This is a cool print test")
    coolprint("This is a cool print test", colorinfo='blue')
    
    # using `with` to not deal with opening and closing files
    with open(TESTFILESDIR + "coolprint_test.txt", "w") as f:
        coolprint("This is a cool print test", file=f)
    with open(TESTFILESDIR+"coolprint_test.txt", "r") as f:
        lines = f.readlines()
    assert lines[0].strip() == 'This is a cool print test'

    with open(TESTFILESDIR + "coolprint_test_red.txt", "w") as f:
        coolprint("This is a cool print test", colorinfo='red', file=f)
    with open(TESTFILESDIR+"coolprint_test_red.txt", "r") as f:
        lines = f.readlines()
    assert lines[0].strip() == 'This is a cool print test'


# =========================================================================

"""
Tests below are generated by chatgpt.
Further testing will be done when the functionality is more in use.
"""


def strip_ansi(text):
    """Remove ANSI escape codes (for tests)."""
    return re.sub(r'\x1b\[[0-9;]*m', '', text)


def test_infoprint():
    buf = io.StringIO()
    wprinting.infoprint("info message", file=buf)
    assert strip_ansi(buf.getvalue()).strip() == "[INFO] info message"


def test_debugprint():
    buf = io.StringIO()
    wprinting.debugprint("debug value", 123, file=buf)
    assert strip_ansi(buf.getvalue()).strip() == "[DEBUG] debug value 123"


def test_printtest():
    buf = io.StringIO()
    wprinting.printtest("test log", file=buf)
    assert strip_ansi(buf.getvalue()).strip() == "[TESTPRINT] test log"


def test_debugfunc_level(monkeypatch):
    monkeypatch.setattr(wprinting, "level", 1)
    buf = io.StringIO()
    monkeypatch.setattr(wprinting, "PRINT_TARGET", buf)
    wprinting.debugfunc("debug message", tag="FUNC")
    assert "[DEBUG][FUNC] debug message" in strip_ansi(buf.getvalue())


def test_debugfunc_level_low(monkeypatch):
    monkeypatch.setattr(wprinting, "level", 0)
    buf = io.StringIO()
    monkeypatch.setattr(wprinting, "PRINT_TARGET", buf)
    wprinting.debugfunc("no print", tag="FUNC")
    assert buf.getvalue() == ""


def test_debug_deep_level(monkeypatch):
    monkeypatch.setattr(wprinting, "level", 2)
    buf = io.StringIO()
    monkeypatch.setattr(wprinting, "PRINT_TARGET", buf)
    wprinting.debug_deep("deep info", tag="DEEP")
    assert "[DEBUG DEEP][DEEP] deep info" in strip_ansi(buf.getvalue())


def test_debug_deep_level_low(monkeypatch):
    monkeypatch.setattr(wprinting, "level", 1)
    buf = io.StringIO()
    monkeypatch.setattr(wprinting, "PRINT_TARGET", buf)
    wprinting.debug_deep("should not print", tag="DEEP")
    assert buf.getvalue() == ""


def test_use_print_target_context_manager():
    buf = io.StringIO()
    with wprinting.use_print_target(buf):
        wprinting.infoprint("scoped")
    assert "[INFO] scoped" in strip_ansi(buf.getvalue())
    # it is not closed now
    assert not buf.closed
    buf.close()
    assert buf.closed


def test_separatorprint_with_title():
    buf = io.StringIO()
    wprinting.separatorprint("Section Header", file=buf)
    out = strip_ansi(buf.getvalue()).strip()
    assert "Section Header" in out
    assert out.startswith("-" * 15)


def test_separatorprint_without_title():
    buf = io.StringIO()
    wprinting.separatorprint(file=buf)
    out = strip_ansi(buf.getvalue()).strip()
    assert out.startswith("-" * 15)


def test_coolprint_gpt(monkeypatch):
    # Patch rich_print to go to buffer
    monkeypatch.setattr(wprinting, "rich_print", lambda *a, **kw: print(*a, file=kw.get("file")))
    buf = io.StringIO()
    wprinting.coolprint("cool styled", file=buf, colorinfo="italic blue")
    assert "[italic blue]cool styled[/italic blue]" in buf.getvalue()


def test__styled_print_terminal(monkeypatch):
    buf = io.StringIO()
    # Fake a terminal with isatty = True
    monkeypatch.setattr(buf, "isatty", lambda: True)
    wprinting._styled_print("LABEL", "93", "styled msg", file=buf)
    value = buf.getvalue()
    assert "\033[93m" in value
    assert "[LABEL] styled msg" in value


def test__styled_print_non_terminal(monkeypatch):
    buf = io.StringIO()
    # Fake a non-terminal (no isatty or returns False)
    monkeypatch.setattr(buf, "isatty", lambda: False)
    wprinting._styled_print("LABEL", "93", "plain msg", file=buf)
    value = buf.getvalue()
    assert value.strip() == "[LABEL] plain msg"

